### ISSUE TITLE
H7 Quopa

### ISSUE THREAD

**Issue by michael9544** [FlightOne/FalcoX-Issue-Tracker#256]
all version

if the Motobeep was used after quopa, the engine sometimes turns in the wrong direction

**Comment by PGIII** [comment]
how soon are you using motor beep after ?

**Comment by michael9544** [comment]
shortly after.
switch down, off
switch middle, beep
switch up, quopa

**Comment by PGIII** [comment]
> shortly after.
> switch down, off
> switch middle, beep
> switch up, quopa

They both send commands to the motors so you probably need to wait a few seconds between using the two modes, we could probably add something to protect you from doing it to quick although the timing is likely different between ESCs. But you can also change the order so that the Beep is the end position for now so that you aren't going past it to use quopa mode, or use a different switch

**Comment by michael9544** [comment]
Thank you.

unfortunately channel 8 is permanently occupied by rssi.
if channel 8 were freely usable, it would make things easier.
