### ISSUE TITLE
The setup process on the T-MOTOR MINI Racer F7 feels very slow and heavy

### ISSUE THREAD

**Issue by Saqoosha** [FlightOne/FalcoX-Issue-Tracker#310]
**Version**
10.2.5.6067

**Target**
TmotorPacerF7

**Describe the bug**
The initial setup runs extremely slow. The stick response is also terrible. It's not that it doesn't respond, but it feels like the CPU is under a huge workload. This prevents the setup from being completed.

**To Reproduce**
Install 10.2.5.6067 to T-MOTOR MINI Racer F7 with TmotorPacerF7 target.

**Expected behavior**
It responds immediately to stick operation and completes setup smoothly.

**Additional context**
I have noticed that the gyro has changed from MPU6000 to BMI270 on the recent version of MINI Racer F7.
Earlier versions that used the MPU6000 did not have this problem and worked with the TmotorPacerF7 target with no problems at all.
http://en.tmotorhobby.com/goods.php?id=1172
![Screen Shot 2022-07-17 at 21 40 50](https://user-images.githubusercontent.com/27694/179404340-20db0f9d-bfc8-4f1e-97ff-a8235fae7fc2.png)

**Comment by PGIII** [comment]
If it has the bmi270 gyro then that is likely the issue, those gyros aren't supported currently. possibly in the future since I know a lot of manufactures are switching to those since they're the only ones they can get but I'm not sure how well they'll fly since I've never used that gyro and they have much slower data rates I believe
