### ISSUE TITLE
PWM 96khz with Dshot64 De sync issues over 15% throttle

### ISSUE THREAD

**Issue by RoninMedia12** [FlightOne/FalcoX-Issue-Tracker#60]
**Version**
Version 10.0.6.3923 Beta 6 Patch 10

**Target**
RevoltOSD

**Describe the bug**
New Setup On Apex Frame, 6s Holybro Tekko32f3 Metal 4 in1 (65A) ESC, Dshot64 mixed with PWM 96Khz Auto motor timing, Demag Low caused Desyncs at anyhing over 15% throttle.   Tested motor idle 10-15 still occurs,    

Also Tested Demag High same issues occur Have not tested any other motor timings other then Auto.  Seen others report the issue on FB and in discord chat but only answer was really to switch back to 48KHZ.  Others tested multiple motor timings.  Did see one guy get it to work pretty well on 4s only.  I can try 4s but want it to work properly on 6s please.  

When I switch back to Dshot32, pwm 96khz with demag low, idle 12-14 quad flies pretty good.  

Would it be better to Run Dshot64 @ 48Khz or  Dshot32 @ 96khz?  

Link to updated the current version I have. https://shop.holybro.com/tekko32f3-metal-4in1-esc65a_p1126.html    

**To Reproduce**
1. Change Blheli32 esc pwm to (96Khz)
2. enable Dshot64 In Falcox OSD
3. Save fly 
4. Desync crash.. 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by PGIII** [comment]
Sounds more like a blheli issue rather than anything on our end, but Dshot64 is dshot2400 at 32khz and dshot32 is dshot1200 at 32khz, so which ever flys better on your escs is probably the best to go with, usually dshot64 is actually less cpu intensive for the FC and ESC and gets the packet transferred quicker, but could be more senstive to noise. 96khz on the esc would probably have the biggest affect on how it flys, where as the differnce between dshot64 and dshot32 wouldnt be as noticable
